"""Initial migration

Revision ID: 0d14befc0ec0
Revises: 
Create Date: 2024-11-16 16:17:57.229277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d14befc0ec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_ambito', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_ambito')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_table('centros_poblados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_centro_poblado', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_centro_poblado')
    )
    op.create_table('remitentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.Text(), nullable=True),
    sa.Column('apellido_paterno', sa.Text(), nullable=True),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'femenino', name='generoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('caserios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_caserio', sa.Text(), nullable=True),
    sa.Column('centro_poblado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_poblado_id'], ['centros_poblados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_caserio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caserios')
    op.drop_table('roles')
    op.drop_table('remitentes')
    op.drop_table('centros_poblados')
    op.drop_table('categorias')
    op.drop_table('ambitos')
    # ### end Alembic commands ###
