"""creacion_tabla_detalle_derivacion

Revision ID: 20a0e62a064c
Revises: eb70d1cdcba4
Create Date: 2025-01-06 15:34:15.732167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a0e62a064c'
down_revision: Union[str, None] = 'eb70d1cdcba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_derivaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('iniciada', 'recepcionada', 'en_progreso', 'finalizada', 'rechazada', 'reasignada', 'archivado', name='estadoderivacionenum'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('usuario_recepcion_id', sa.Integer(), nullable=True),
    sa.Column('derivacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['derivacion_id'], ['derivaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_derivaciones')
    # ### end Alembic commands ###
