"""Fix foreign key ambiguity

Revision ID: 2fd210dde28a
Revises: d6d13b1c0558
Create Date: 2024-11-19 10:40:35.573173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd210dde28a'
down_revision: Union[str, None] = 'd6d13b1c0558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_ambito', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_ambito')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_area', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_area')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_table('centros_poblados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_centro_poblado', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_centro_poblado')
    )
    op.create_table('remitentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.Text(), nullable=True),
    sa.Column('apellido_paterno', sa.Text(), nullable=True),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'femenino', name='generoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('caserios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_caserio', sa.Text(), nullable=True),
    sa.Column('centro_poblado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_poblado_id'], ['centros_poblados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_caserio')
    )
    op.create_table('comunicacion_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_origen_id', sa.Integer(), nullable=False),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_origen_id', 'area_destino_id', name='unique_area_comunicacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicacion_areas')
    op.drop_table('caserios')
    op.drop_table('roles')
    op.drop_table('remitentes')
    op.drop_table('centros_poblados')
    op.drop_table('categorias')
    op.drop_table('areas')
    op.drop_table('ambitos')
    # ### end Alembic commands ###
