"""renombrar_columna_usuario_recepcion_id_por_usuario_movimiento_id

Revision ID: 39be6c9769dd
Revises: fbb0863e1c0b
Create Date: 2025-01-31 16:14:21.157630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39be6c9769dd'
down_revision: Union[str, None] = 'fbb0863e1c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_derivaciones', sa.Column('usuario_movimiento_id', sa.Integer(), nullable=True))
    op.drop_column('detalles_derivaciones', 'usuario_recepcion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_derivaciones', sa.Column('usuario_recepcion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('detalles_derivaciones', 'usuario_movimiento_id')
    # ### end Alembic commands ###
