"""creacion_tabla_comunicacion_areas

Revision ID: 49122d5bec1e
Revises: 6b65c4161f17
Create Date: 2024-11-18 16:10:01.644628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49122d5bec1e'
down_revision: Union[str, None] = '6b65c4161f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicacion_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_origen_id', sa.Integer(), nullable=False),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicacion_areas')
    # ### end Alembic commands ###
