"""creacion_migracion_usuarios

Revision ID: 55202efdc6ac
Revises: 6814bfc6c221
Create Date: 2024-12-01 23:41:04.784075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55202efdc6ac'
down_revision: Union[str, None] = '6814bfc6c221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.Text(), nullable=True),
    sa.Column('contrasena', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trabajador_id')
    )
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_index(op.f('ix_caserios_centro_poblado_id'), 'caserios', ['centro_poblado_id'], unique=False)
    op.create_index(op.f('ix_comunicacion_areas_area_origen_id'), 'comunicacion_areas', ['area_origen_id'], unique=False)
    op.create_index(op.f('ix_remitentes_apellido_paterno'), 'remitentes', ['apellido_paterno'], unique=False)
    op.create_index(op.f('ix_remitentes_nombres'), 'remitentes', ['nombres'], unique=False)
    op.create_index(op.f('ix_trabajadores_apellido_paterno'), 'trabajadores', ['apellido_paterno'], unique=False)
    op.create_index(op.f('ix_trabajadores_area_id'), 'trabajadores', ['area_id'], unique=False)
    op.create_index(op.f('ix_trabajadores_nombres'), 'trabajadores', ['nombres'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trabajadores_nombres'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_area_id'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_apellido_paterno'), table_name='trabajadores')
    op.drop_index(op.f('ix_remitentes_nombres'), table_name='remitentes')
    op.drop_index(op.f('ix_remitentes_apellido_paterno'), table_name='remitentes')
    op.drop_index(op.f('ix_comunicacion_areas_area_origen_id'), table_name='comunicacion_areas')
    op.drop_index(op.f('ix_caserios_centro_poblado_id'), table_name='caserios')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
