"""creacion_tabla_estado_documento

Revision ID: 8c32e1218f18
Revises: 20a0e62a064c
Create Date: 2025-01-07 10:41:10.251199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c32e1218f18'
down_revision: Union[str, None] = '20a0e62a064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ingresado', 'en_proceso', 'archivado', name='estadodocumentoenum'), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estados_documentos')
    # ### end Alembic commands ###
