"""creacion_tabla_documentos

Revision ID: 9cc63e7569b6
Revises: 55202efdc6ac
Create Date: 2024-12-17 10:19:39.645457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc63e7569b6'
down_revision: Union[str, None] = '55202efdc6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('fecha_ingreso', sa.TIMESTAMP(), nullable=True),
    sa.Column('folios', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('asunto', sa.Text(), nullable=True),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('ambito_id', sa.Integer(), nullable=False),
    sa.Column('caserio_id', sa.Integer(), nullable=True),
    sa.Column('centro_poblado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ambito_id'], ['ambitos.id'], ),
    sa.ForeignKeyConstraint(['caserio_id'], ['caserios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['centro_poblado_id'], ['centros_poblados.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['remitentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
