"""agregar_relacion_usuario_derivacion

Revision ID: b6f0e5a92fe5
Revises: b75f112552e6
Create Date: 2025-01-29 15:26:26.730941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f0e5a92fe5'
down_revision: Union[str, None] = 'b75f112552e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derivaciones', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'derivaciones', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'derivaciones', type_='foreignkey')
    op.drop_column('derivaciones', 'usuario_id')
    # ### end Alembic commands ###
