"""agregar_columna_recepcion_tabla_detalle_derivacion

Revision ID: b75f112552e6
Revises: 8c32e1218f18
Create Date: 2025-01-29 08:51:56.510788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75f112552e6'
down_revision: Union[str, None] = '8c32e1218f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_derivaciones', sa.Column('recepcionada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalles_derivaciones', 'recepcionada')
    # ### end Alembic commands ###
