"""renombrar_columna_tabla_detalle_derivacion

Revision ID: bf3769050b2a
Revises: 39be6c9769dd
Create Date: 2025-01-31 16:16:37.444145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3769050b2a'
down_revision: Union[str, None] = '39be6c9769dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_derivaciones', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.drop_column('detalles_derivaciones', 'usuario_movimiento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_derivaciones', sa.Column('usuario_movimiento_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('detalles_derivaciones', 'usuario_id')
    # ### end Alembic commands ###
