"""crear_tabla_notificacion

Revision ID: c7b433699cdc
Revises: bf3769050b2a
Create Date: 2025-02-05 09:38:30.225860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b433699cdc'
down_revision: Union[str, None] = 'bf3769050b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
