"""restruiccion_unica_tabla_comunicaciones

Revision ID: d6d13b1c0558
Revises: 49122d5bec1e
Create Date: 2024-11-18 18:35:48.150329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d13b1c0558'
down_revision: Union[str, None] = '49122d5bec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
