"""creacion_tabla_derivacion

Revision ID: eb70d1cdcba4
Revises: f322129528c9
Create Date: 2025-01-03 15:16:53.225340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb70d1cdcba4'
down_revision: Union[str, None] = 'f322129528c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('area_origen_id', sa.Integer(), nullable=False),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derivaciones')
    # ### end Alembic commands ###
