"""creacion_tabla_recepcion_documentos

Revision ID: f322129528c9
Revises: 9cc63e7569b6
Create Date: 2025-01-03 08:33:24.975697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f322129528c9'
down_revision: Union[str, None] = '9cc63e7569b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepcion_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_recepcion', sa.TIMESTAMP(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepcion_documentos')
    # ### end Alembic commands ###
