"""agregar_eliminaciones_cascada

Revision ID: fbb0863e1c0b
Revises: b6f0e5a92fe5
Create Date: 2025-01-31 12:26:00.080780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb0863e1c0b'
down_revision: Union[str, None] = 'b6f0e5a92fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('derivaciones_documento_id_fkey', 'derivaciones', type_='foreignkey')
    op.create_foreign_key(None, 'derivaciones', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detalles_derivaciones_derivacion_id_fkey', 'detalles_derivaciones', type_='foreignkey')
    op.create_foreign_key(None, 'detalles_derivaciones', 'derivaciones', ['derivacion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('estados_documentos_documento_id_fkey', 'estados_documentos', type_='foreignkey')
    op.create_foreign_key(None, 'estados_documentos', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recepcion_documentos_documento_id_fkey', 'recepcion_documentos', type_='foreignkey')
    op.create_foreign_key(None, 'recepcion_documentos', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recepcion_documentos', type_='foreignkey')
    op.create_foreign_key('recepcion_documentos_documento_id_fkey', 'recepcion_documentos', 'documentos', ['documento_id'], ['id'])
    op.drop_constraint(None, 'estados_documentos', type_='foreignkey')
    op.create_foreign_key('estados_documentos_documento_id_fkey', 'estados_documentos', 'documentos', ['documento_id'], ['id'])
    op.drop_constraint(None, 'detalles_derivaciones', type_='foreignkey')
    op.create_foreign_key('detalles_derivaciones_derivacion_id_fkey', 'detalles_derivaciones', 'derivaciones', ['derivacion_id'], ['id'])
    op.drop_constraint(None, 'derivaciones', type_='foreignkey')
    op.create_foreign_key('derivaciones_documento_id_fkey', 'derivaciones', 'documentos', ['documento_id'], ['id'])
    # ### end Alembic commands ###
